"""Interfaces (Protocols) que la capa application consume.

Implementaciones concretas viven en infrastructure/. NUNCA importar SQLAlchemy aquí.
"""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .entities import Membership, Organization


class OrganizationRepository(Protocol):
    async def get(self, id: UUID) -> Organization | None: ...
    async def get_by_slug(self, slug: str) -> Organization | None: ...
    async def save(self, org: Organization) -> None: ...
    async def list_for_user(self, user_id: UUID) -> list[Organization]: ...


class MembershipRepository(Protocol):
    async def get(self, id: UUID) -> Membership | None: ...
    async def list_for_user(self, user_id: UUID) -> list[Membership]: ...
    async def list_for_organization(self, organization_id: UUID) -> list[Membership]: ...
    async def save(self, m: Membership) -> None: ...
